import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Rove</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script src="https://cdn.tailwindcss.com"></Script>
    </>
  )
}
